version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres-db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-networks

  project:
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./project/.env
    depends_on:
      - postgres-db
      - redis
    volumes:
      - ./project:/app
      - /app/node_modules
    command: sh -c "npm run build && npm run start"

volumes:
  pgdata:
  redis_data:
    driver: local
