version: "3.8"

networks:
  learn-cache-networks:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - learn-cache-networks

  postgres-db:
    image: postgres:15
    container_name: postgres_cache
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - learn-cache-networks

  project:
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./project/.env
    networks:
      - learn-cache-networks
    depends_on:
      - postgres-db
      - redis
    volumes:
      - ./project:/app
      - /app/node_modules
    command: npm run start

volumes:
  pgdata:
  redis_data:
    driver: local
